apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-openshift.tanzu.japan.com.1.5.1
spec:
  refName: tap-openshift.tanzu.japan.com
  version: 1.5.1
  valuesSchema:
    openAPIv3:
      title: tap-openshift.tanzu-jp values schema
      properties:
        sessions:
          type: integer
          description: session count
          default: 5
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-openshift
          ref: origin/pkgr
          subPath: k8s/
      template:
      - ytt: {}
      deploy:
      - kapp: {}
