apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-openshift.tanzu.japan.com.1.5.1
spec:
  refName: tap-openshift.tanzu.japan.com
  version: 1.5.1
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-openshift
          ref: origin/pkgr
          subPath: k8s/
      template:
      - ytt: {}
      deploy:
      - kapp: {}
