apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tap-openshift.tanzu.japan.com
spec:
  displayName: "TAP on OpenShift"
  shortDescription: "TAP on OpenShift"
  supportDescription: "https://carvel.dev/"
  providerName: "VMware"
  maintainers:
  - name: "Machi Hoshino"
