#@ load("@ytt:data", "data")

#@ wildcard = "*." + data.values.domain
#@ wildcard_array = [ wildcard ]
#@ namespace = "learningcenter"

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "portal"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tap-openshift-issuer
  namespace: #@ namespace
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting portal"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-openshift-issuer-cert
  namespace: #@ namespace
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting portal"
spec:
  secretName: #@ data.values.domain + "-tls"
  issuerRef: 
    kind: Issuer
    name: tap-openshift-issuer
  commonName: #@ wildcard
  dnsNames: #@ wildcard_array
