#@ load("@ytt:data", "data")

apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: #@ data.values.hostname
spec:
  portal:
    ingress:
      hostname: #@ data.values.hostname
      domain: #@ data.values.domain
      #@ if/end data.values.tls.enabled:
      secret: #@ data.values.domain + "-tls"
    registration:
      type: anonymous
    reserved: 0
    sessions:
      maximum: #@ data.values.sessions
    updates:
      workshop: true
  workshops:
  - expires: 240m
    name: tap-openshift
    orphaned: 240m
