apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tap-openshift
spec:
  portal:
    ingress:
      hostname: tap-openshift
    registration:
      type: anonymous
    reserved: 0
    sessions:
      maximum: 25
    updates:
      workshop: true
  workshops:
  - expires: 240m
    name: tap-openshift
    orphaned: 240m
