#@ load("@ytt:data", "data")

apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-openshift
spec:
  title: TAP on OpenShift
  description: TAP on OpenShift seminar
  url: https://github.com/mhoshi-vm/tap-openshift-jp
  content:
    image: ghcr.io/mhoshi-vm/tap-openshift-lc:latest
    files: github.com/mhoshi-vm/tap-openshift-jp?ref=main
  session:
    env:
    - name: TANZUNET_TOKEN
      value: #@ data.values.tanzunet
    - name: TAP_VERSION
      value: #@ data.values.tapversion
    applications:
      editor:
        enabled: true
        layout: lower
      terminal:
        enabled: true
        layout: split
    dashboards:
    - name: Gitea
      url: http://gitea:3000
    objects:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: $(workshop_namespace)-workshop-read-crb
          namespace: $(workshop_namespace)
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: $(service_account)
      - apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          labels:
            run: gitea
          name: gitea
          namespace: $(workshop_namespace)
        spec:
          containers:
          - image: #@ data.values.giteaimage
            name: gitea
            env:
            - name: GITEA_WORK_DIR
              value: /tmp
            resources: {}
            securityContext:
              capabilities:
                drop:
                - ALL
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
              runAsUser: 1000
          dnsPolicy: ClusterFirst
          restartPolicy: Always
