apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-openshift
spec:
  title: TAP on OpenShift
  description: TAP on OpenShift seminar
  url: https://github.com/mhoshi-vm/tap-openshift-jp
  content:
    image: ghcr.io/mhoshi-vm/tap-openshift-lc-image
  session:
    applications:
      console:
        enabled: true
      docker:
        enabled: true
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
