#@ load("@ytt:data", "data")

apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-openshift
spec:
  title: TAP on OpenShift
  description: TAP on OpenShift seminar
  url: https://github.com/mhoshi-vm/tap-openshift-jp
  content:
    image: ghcr.io/mhoshi-vm/tap-openshift-lc:latest
    files: https://github.com/mhoshi-vm/tap-openshift-jp/workshop
  session:
    applications:
      editor:
        enabled: true
      terminal:
        enabled: true
        layout: split
    dashboards:
    - name: TAP_GUI
      url: #@ data.values.tapgui
    objects:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: $(session_namespace)-workshop-read-crb
          namespace: $(session_namespace)
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: $(service_account)
